### ISSUE TITLE
Грейд зависимостей `text-transform`, `upload`, `sidebar`, `portal`, `modal`

### ISSUE THREAD

**Issue by Nelfimov** [atls/hyperion#492]
### С чем связан запрос на фичу?

Обновление пировых и билд зависимостей под актуальные

### Расскажите как вы это себе видите

Необходимо прогрейдить все зависимости `@atls-ui-parts` и `@atls-ui-proto` у `text-transform`, `upload`, `sidebar`, `portal`, `modal` под актуальные пакеты.

Важное примечание:
- пакеты `@emotion` оставить на версии 11.9.х.
- не использовать `^`, только жесткие версии

### Definition of done (критерий готовности)

`yarn check` проходит без ошибок, версии обновлены до максимально последних, истории `design` с компонентом работают.

**Comment by AlinaLaniuk** [comment]
Не понимаю некоторых моментов по выполнению таски.
При обновлении пакета ui-parts/sidebar падает ошибка.

**Воспроизведение ошибки**

- иду в воркспейс
- yarn workspace @atls-ui-parts/sidebar add framer-motion@latest.
- падает ошибка, пакет не обновляется
- Ожидаемое поведение
- Обновление пакета, отсутствие ошибок после команд yarn check и yarn test unit

**Логи**
(node:23650) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Usage Error: Package "framer-motion" is already listed as a regular dependency - remove the -D,-P flags or remove it from your dependencies first
$ yarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

**Действия**
Обновляю пакеты так:

иду в пакет @atls-ui-parts/sidebar
команда yarn workspace <имя воркспейса> add <--dev --peer или без флага, если нужно обновить обычные зависимости> <имя пакета>@latest.
после обновления всех пакетов, иду в корневую директорию проекта, устанавливаю по новой зависимости, делаю yarn check и yarn test unit

**Вопросы**
**По ошибке:**

При обновлении @atls-ui-parts/sidebar падает ошибка.
Ну и то же самое при попытке обновить пир зависимости. Что с этим делать?

**Также не понимаю несколько моментов, помогите.**

- При обновлении peerDependencies в пакетах появляется знак *.

Пример (воркспейс @atls-ui-parts/upload):
"devDependencies": {
"@atls-ui-parts/avatar": "workspace:^",
"@types/node": "20.5.7",
"@types/react": "18.2.21",
"graphql": "16.8.0",
"react": "18.2.0"
},
"peerDependencies": {
"graphql": "",
"react": ""
}
Я не понимаю, это значит "версия пакета такая же, как указана выше в devDependencies" или "версия пакета такая же, как указана у ''родителя". Так оставлять можно? Или указывать пакет ручками?

- В таске указано, что версии должны быть жесткими. Когда команда yarn add с тегом latest отрабатывает, автоматически указывается диапазон. Правильно понимаю, что сделать версию жесткой - значит просто убрать руками ^ ?

- Не понимаю, что делать с зависимостями на воркспейс. Например, при обновлении devDependencies @atls-ui-parts/upload зависимость на @atls-ui-parts/avatar выглядит так:

"devDependencies": {
"@atls-ui-parts/avatar": "workspace:^",
},
Если я правильно понимаю, это значит, что будет взята версия, которая указана в package.json соответствующего пакета и выше. Но опять же, как правильно сделать? Прописать руками последнюю версию пакета жестко?

- В критериях готовности указано: yarn check проходит без ошибок, версии обновлены до максимально последних, истории design с компонентом работают. Что означает вот эта часть: истории design с компонентом работают?

**Comment by SlumberyDude** [comment]
@AlinaLaniuk 

> иду в воркспейс

Команды через `yarn workspace ... ` можно делать прямо из корня проекта, не обязательно ходить каждый раз в воркспейс. Это так, наблюдение.

> (node:23650) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use node --trace-deprecation ... to show where the warning was created)

Вот эта часть в логах не относится к ошибке, это ворнинг. Он часто встречается, пока что можешь его игнорировать.

> Usage Error: Package "framer-motion" is already listed as a regular dependency - remove the -D,-P flags or remove it from your dependencies first

Исходя из текста ошибки он не понимает, что есть более новая версия и пишет что "зависимость и так есть, что еще хочешь". Посмотри в [npm регистре](https://www.npmjs.com/package/framer-motion), какая последняя версия пакета и пиши ее явно `yarn workspace @atls-ui-parts/sidebar add framer-motion@10.16.1` Иногда IDE при наведении курсора подсказывает, какая сейчас версия самая свежая.

> При обновлении peerDependencies в пакетах появляется знак *.

Это значит, что самая последняя доступная версия, это нам не подходит, нужна конкретная цифра, иначе когда пакет обновится, то у нас что-то может *внезапно* сломаться.

> Так оставлять можно? Или указывать пакет ручками? 

Ага, указывай явно.

> В таске указано, что версии должны быть жесткими. Когда команда yarn add с тегом latest отрабатывает, автоматически указывается диапазон. Правильно понимаю, что сделать версию жесткой - значит просто убрать руками ^ ?

Чтобы установить конкретную версию используй ключ `-E` или `--exact`, [тут более подробно](https://classic.yarnpkg.com/lang/en/docs/cli/add/)



> Не понимаю, что делать с зависимостями на воркспейс. Например, при обновлении devDependencies @atls-ui-parts/upload зависимость на @atls-ui-parts/avatar выглядит так:
```json
    "devDependencies": {
        "@atls-ui-parts/avatar": "workspace:^",
    },
```

Воркспейсы ссылаются друг на друга, при обновлении они по идее не должны меняться. Какая именно команда обновления зависимости меняет воркспейс?

> Если я правильно понимаю, это значит, что будет взята версия, которая указана в package.json соответствующего пакета и выше. Но опять же, как правильно сделать? Прописать руками последнюю версию пакета жестко?

Это странно, что воркспейс зависимость вообще поменялась. Какая команда ее поменала?

> В критериях готовности указано: yarn check проходит без ошибок, версии обновлены до максимально последних, истории design с компонентом работают. Что означает вот эта часть: истории design с компонентом работают?

Я не уверен, но возможно это связано со сторибуком, а конкретно с историями в директории `ui/design`

**Comment by AlinaLaniuk** [comment]
@SlumberyDude 

>Воркспейсы ссылаются друг на друга, при обновлении они по идее не должны меняться. Какая именно команда обновления зависимости меняет воркспейс?
Это странно, что воркспейс зависимость вообще поменялась. Какая команда ее поменала?

Ну я сделала yarn workspace @atls-ui-parts/upload add @atls-ui-parts/avatar@latest. Их не надо трогать?) или как?

>Исходя из текста ошибки он не понимает, что есть более новая версия и пишет что "зависимость и так есть, что еще хочешь". Посмотри в [npm регистре](https://www.npmjs.com/package/framer-motion), какая последняя версия пакета и пиши ее явно yarn workspace @atls-ui-parts/sidebar add framer-motion@10.16.1 Иногда IDE при наведении курсора подсказывает, какая сейчас версия самая свежая.

Погоди, он тут как будто ругается на то, что одни и те же зависимости есть и в dependencies, и в peerDependencies. То есть у меня вообще не получается их обновить. Или нет?)

**Comment by SlumberyDude** [comment]
@AlinaLaniuk 

> Ну я сделала yarn workspace @atls-ui-parts/upload add @atls-ui-parts/avatar@latest. Их не надо трогать?) или как?

Не, внутренние зависимости не трогай, только внешние. Ну те, где стоит ссылка как `workspace..` трогать не надо.

> Погоди, он тут как будто ругается на то, что одни и те же зависимости есть и в dependencies, и в peerDependencies. То есть у меня вообще не получается их обновить. Или нет?)

Это нормально, что там зависимости одни и те же. Пиры нужны для конечного пользователя, а дев для нас как разработчиков. Есть зависимость и в пирах и в дев, то можно обновить сразу оба добавив несколько ключей `-PD` вот так. Подробнее о пир зависимостях можешь почитать [тут](https://github.com/atls/hyperion/wiki/%D0%A7%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-peerDependencies)

**Comment by Nelfimov** [comment]
Вообще по `peerDependencies` можешь почитать у нас - https://github.com/atls/hyperion/wiki/Что-такое-peerDependencies

> Ну я сделала yarn workspace @atls-ui-parts/upload add @atls-ui-parts/avatar@latest. Их не надо трогать?) или как?
Обрати внимание, что это локальный пакет. Ты можешь рядом посмотреть его версию, чтобы все соответствовало.

> Погоди, он тут как будто ругается на то, что одни и те же зависимости есть и в dependencies, и в peerDependencies. То есть у меня вообще не получается их обновить. Или нет?)

Из смысла `peerDependencies` - ты туда вставляешь те пакеты, которые ожидаешь от "родителей". Туда имеет смысл добавить `react`, `next`, т.е. те пакеты, что и так будут в твоем проекте.
`dependencies` же используются чтобы сбилдить проект, не требуя ничего ни от кого.

`devDependencies` - то что тебе нужно для локальной разработки.

**И получается, что ты требуешь разные версии одного и того же пакета.**

Если хочешь посмотреть как, например, `framer-motion` используется в других наших пакетах, можешь заглянуть в `ui-parts/select`.

Если уж сильно хочется, то можно хоть руками править `package.json` и версии пакетов, но тогда ты не столкнешься с проблемой которую описал выше.

**Comment by AlinaLaniuk** [comment]
@Nelfimov 
сорри, мне все равно не понятно)

я прочла материал трижды, и как будто в рамках стать все понятно. 

не понимаю, как это работает в проекте.

Родитель - это корневой package.json. Там прописаны зависимости, которые будут юзаться всеми пакетами репозитория. И когда мы что-то указываем в peerDependencies у конкретного пакета, это значит, "сходи попроси у моего родителя, своего не имею". Так?

Тут плиз, укажи, а где смотреть эти общие зависимости, если у корневого package.json вообще не указаны dependencies. Или, если я ошибаюсь, кто для того же @atls-ui-parts/sidebar будет родителем?

пробелма с той ошибкой заключается в том, как выглядит package.json воркспейса  @atls-ui-parts/sidebar

Вот он полностью

```
{
  "name": "@atls-ui-parts/sidebar",
  "version": "0.0.8",
  "license": "MIT",
  "main": "src/index.ts",
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "yarn library build",
    "prepack": "yarn run build",
    "postpack": "rm -rf dist"
  },
  "dependencies": {
    "@emotion/styled": "^11.9.3",
    "framer-motion": "6.3.11",
    "react": "^18.2.0"
  },
  "devDependencies": {
    "@atls-ui-parts/layout": "workspace:^",
    "@atls-ui-parts/switch": "workspace:^",
    "@emotion/css": "11.9.0",
    "@fortawesome/fontawesome-svg-core": "6.4.2",
    "@fortawesome/free-solid-svg-icons": "6.4.2",
    "@fortawesome/react-fontawesome": "0.2.0",
    "@types/styled-system": "5.1.17",
    "styled-system": "5.1.5",
    "styled-tools": "1.7.2"
  },
  "peerDependencies": {
    "@emotion/styled": "11.3.0",
    "framer-motion": "4.1.17",
    "react": "^17.0.2",
    "styled-system": "5.1.5",
    "styled-tools": "1.7.2"
  },
  "publishConfig": {
    "access": "public",
    "main": "dist/index.js",
    "typings": "dist/index.d.ts"
  }
}
```

Если ставить farmer-motion как обычную зависимость, ошибка такая:

`Usage Error: Package "react" is already listed as a regular dependency - remove the -D,-P flags or remove it from your dependencies first`

Если как пир зависимость, такая:

`Usage Error: Package "react" is already listed as a regular dependency - remove the -D,-P flags or remove it from your dependencies first`

Здесь react и frame-motion указаны и в peerDependencies, и в просто dependencies. Это точно так и должно быть? Вроде как пакет просит свою версию react и framer-motion, а еще такой "и родительскую мне подгоните".

**Comment by Nelfimov** [comment]
https://github.com/atls/hyperion/pull/496
